name: Build and Deploy Microservice

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set executable permissions for gradlew
      run: chmod +x gradlew

    - name: Build and Test
      run: |
        cd Department
        ./gradlew build
    

    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        context: ./Department
        


